### ISSUE TITLE
Write trades into a sql database

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#194]
Follow-up issues: #317 and #318 

## Desired Behavior
I want to be able to access all the trades executed by the bot in a database

## Impact
The desired behavior will allow me to better work with kelp trades

## Feature Suggestion
We can achieve the desired behavior by writing to the database as a fill tracking handler

## References
depends on this bug: https://github.com/stellar/kelp/issues/193

## Tasks
- [x] port commits:
    - [x] https://github.com/nikhilsaraf/kelp/commit/0c9db72cc2847a06debdbf59d3a31a83cba31146
    - [x] https://github.com/nikhilsaraf/kelp/commit/50fad164d49317c151638babd78983d94bca273d
    - [x] https://github.com/nikhilsaraf/kelp/commit/17402f41f6cdc3e3501f55c8895b556050ff44b8
    - [x] https://github.com/nikhilsaraf/kelp/commit/626580ab54474975bad7c31351ac72783bb83cf2
    - [x] https://github.com/nikhilsaraf/kelp/commit/4121ea8549ba9ef098c1febed172c415d07b0bfc
    - [x] https://github.com/nikhilsaraf/kelp/commit/c11e700280421176687c4621ef97226c8c022163
- [x] switch to a better db driver that can cross-compile, such as a postgres driver
- [x] save asset issuers in db table (or foreign key to a `markets` table)
- [x] use date types on date fields
- [x] fix schema for trades table
- [x] correct number of decimals for precision of float values
- [x] composite primary key on trades table (market_id and txid)
- [x] should provide a graceful failure mode experience when using without an installed postgres db, or one we cannot connect to
- [x] add version number to the database and version numbers per table to know when they are upgraded (maybe in the same table with a column specifying table vs. db)

### Testing
- [x] test compiles and runs on local machine for local platform (OS, arch)

**Comment by nikhilsaraf** [comment]
needs CGO_ENABLED for sqlite to work for cross-compiling to linux
compiling directly on a linux system works without cgo enabled
