### ISSUE TITLE
[Epic] [8] streamline network requests

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#467]
we are making too many network calls for basic information

See experimental profiling options added to binary in this commit ([12ac3ce9d4d27acd57da0f9d6edeecdf671e1f4f](https://github.com/stellar/kelp/commit/12ac3ce9d4d27acd57da0f9d6edeecdf671e1f4f))

- ~[ ] ieif makes multiple requests and has added a layer of complexity with caching, which can probably be removed once streamlined~ (moved to issue #650)

----
## Done in Sprint 5
- [x] [3] low-hanging fruit improvements to networking code that doesn't need redesign ([issue](https://github.com/stellar/kelp/issues/559))
- [x] [2] only reset cached balances and liabilities if pruneOps > 0, reducing unnecessary network calls ([issue](https://github.com/stellar/kelp/issues/561))
- [x] [2] use single call to load offers when resetting liabilities ([issue](https://github.com/stellar/kelp/issues/563))
- [x] ~~[2] Faster network calls using fasthttp ([issue](https://github.com/stellar/kelp/issues/468))~~

**Comment by nikhilsaraf** [comment]
The bot prints out the time taken by the update function for everything except the submit operation.

Benchmarks:
- time for update() with all network requests: ~4.2s
- time for update() with all network requests turned off: 1-2 ms 🔥 

This means we can drive a lot more performance from the bot, I will upload pprof files for the above
