### ISSUE TITLE
[8] follow-on tasks for Kelp CLI data tracking

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#516]
## Desired Behavior
I want to persist state of user preferences and userId in regards to data tracking

## Impact
The desired behavior will allow me to be consistent with user prefs

## Features
- [x] add `isTestnet` field on commonProps (can apply to stellar testnet or sandboxed centralized exchanges) (#530) 
- [x] get deviceID using this library: [machineID](https://github.com/denisbrodbeck/machineid) (#531) 
- [x] user_id should be a hash of the trader account_id on sdex. for centralized exchanges it can be a hash of the API_KEY (#534)
- [x] disable event tracking if `--no-headers` flag specified in cli ([code](https://github.com/stellar/kelp/blob/master/cmd/trade.go#L516)) (#532)
- [x] add support for official amplitude properties (OS, Country, and other user/event properties)
- [x] send time taken to run update function in the update event as `millisForUpdate` and update relevant struct (#533)
- [x] ~extract call to Amplitude sendEvent API in `support/sdk/amplitude.go` (similar to `support/sdk/ccxt.go`)~ (don't need to do now)
- [ ] function to send update event more frequently in first hour and then slow down after that

## Additional context
related to #478
