### ISSUE TITLE
Improve fill tracking for SDEX (faster, better rate limit handling)

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#671]
- [x] parallelize fetching of getOrderAction
- [x] filter by trader account
- [x] better rate limit handling
